import { useEffect, useMemo, useState } from "react";
import { Link, Navigate, useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, ArrowRight, Building2, Check, ChevronRight, ClipboardList, Clock3, FileCheck2, LogOut, MapPin, Package, Route, ShieldCheck, Truck, UserRound, Wallet, Weight, X } from "lucide-react";
import "./Portal.css";

const seedLoads = [
  { id:"LW-2847", cargo:"Paketli kuru gıda", from:"İstanbul / Tuzla", to:"Ankara / Sincan", vehicle:"Tır", weight:"24 ton", price:"38.000 ₺", date:"12 Eyl", status:"Teklif alıyor", offers:6 },
  { id:"LW-2844", cargo:"Paletli tekstil ürünü", from:"İzmir / Bornova", to:"Bursa / Nilüfer", vehicle:"Kamyon", weight:"12 ton", price:"17.500 ₺", date:"13 Eyl", status:"Teklif alıyor", offers:3 },
  { id:"LW-2838", cargo:"Ambalajlı yapı malzemesi", from:"Kocaeli / Gebze", to:"Adana / Seyhan", vehicle:"Tır", weight:"22 ton", price:"42.000 ₺", date:"14 Eyl", status:"Planlandı", offers:9 },
];
const jobs = [
  { id:"LW-2847", cargo:"Paketli kuru gıda", from:"İstanbul / Tuzla", to:"Ankara / Sincan", vehicle:"Tır", weight:"24 ton", price:"38.000 ₺", date:"12 Eylül", distance:"452 km", company:"Kaya Lojistik", match:96 },
  { id:"LW-2844", cargo:"Paletli tekstil ürünü", from:"İzmir / Bornova", to:"Bursa / Nilüfer", vehicle:"Kamyon", weight:"12 ton", price:"17.500 ₺", date:"13 Eylül", distance:"331 km", company:"Demir Nakliyat", match:91 },
  { id:"LW-2838", cargo:"Ambalajlı yapı malzemesi", from:"Kocaeli / Gebze", to:"Adana / Seyhan", vehicle:"Tır", weight:"22 ton", price:"42.000 ₺", date:"14 Eylül", distance:"831 km", company:"Arslan Depo", match:88 },
];
const roleInfo = {
  "yuk-veren": { title:"Yük Veren", description:"İlan yayınlayın, teklifleri karşılaştırın ve sevkiyatınızı takip edin.", icon:Building2 },
  sofor: { title:"Şoför", description:"Size uygun yükleri bulun, teklif verin ve seferlerinizi yönetin.", icon:Truck },
};
const offers = [
  { id:1, load:"LW-2847", driver:"Ahmet Demir", vehicle:"Tır · 34 AB 847", score:"4.9", trips:184, amount:"36.500 ₺", eta:"Bugün 14:30" },
  { id:2, load:"LW-2847", driver:"Mehmet Kaya", vehicle:"Tır · 06 MK 144", score:"4.8", trips:126, amount:"37.250 ₺", eta:"Bugün 16:00" },
  { id:3, load:"LW-2844", driver:"Serkan Yıldız", vehicle:"Kamyon · 35 SY 615", score:"4.7", trips:98, amount:"16.900 ₺", eta:"Yarın 09:00" },
];

function Brand(){return <Link className="portal-brand" to="/"><span><Route size={19}/></span>logiway</Link>}

export function RoleSelect(){return <div className="role-page"><header><Brand/><Link to="/" className="back-link"><ArrowLeft size={16}/> Ana sayfa</Link></header><main><div className="role-intro"><span>LOGIWAY’E HOŞ GELDİNİZ</span><h1>Nasıl devam etmek<br/>istiyorsunuz?</h1><p>Size özel çalışma alanını açmak için rolünüzü seçin.</p></div><div className="role-cards">{Object.entries(roleInfo).map(([key,info])=>{const Icon=info.icon;return <Link to={`/giris/${key}`} className="role-card" key={key}><span className="role-icon"><Icon/></span><div><h2>{info.title} olarak devam et</h2><p>{info.description}</p></div><ChevronRight/></Link>})}<Link to="/dashboard" className="admin-access"><ShieldCheck size={18}/><span><strong>Yönetici girişi</strong><small>Operasyon kontrol merkezi</small></span><ChevronRight size={18}/></Link></div></main></div>}

export function PortalLogin(){
  const {role}=useParams();const navigate=useNavigate();const info=roleInfo[role];const [busy,setBusy]=useState(false);const [register,setRegister]=useState(false);
  if(!info)return <Navigate to="/giris" replace/>;const Icon=info.icon;
  function submit(e){e.preventDefault();setBusy(true);setTimeout(()=>navigate(`/${role}/panel`),450)}
  return <div className="login-page"><div className="login-aside"><Brand/><div><span className="aside-icon"><Icon/></span><h1>{info.title} çalışma alanı</h1><p>{info.description}</p><ul><li><Check/> Ayrı ve güvenli hesap</li><li><Check/> Role özel araçlar</li><li><Check/> Mobil uyumlu kullanım</li></ul></div><small>© 2026 Logiway</small></div><main className="login-main"><Link to="/giris" className="back-link"><ArrowLeft size={16}/> Rol seçimine dön</Link><form onSubmit={submit}><div className="auth-tabs"><button type="button" className={!register?"active":""} onClick={()=>setRegister(false)}>Giriş yap</button><button type="button" className={register?"active":""} onClick={()=>setRegister(true)}>Hesap oluştur</button></div><span className="form-kicker">{info.title.toUpperCase()} {register?"KAYDI":"GİRİŞİ"}</span><h2>{register?"Bilgilerinizi tamamlayın.":"Tekrar hoş geldiniz."}</h2><p>{register?"Size uygun çalışma alanını birkaç adımda hazırlayalım.":"Çalışma alanınıza erişmek için bilgilerinizi girin."}</p>{register&&<><label>{role==="sofor"?"Ad soyad":"Firma unvanı"}<input required placeholder={role==="sofor"?"Adınız ve soyadınız":"Firma adı"}/></label><label>Telefon numarası<input required type="tel" placeholder="05xx xxx xx xx"/></label>{role==="sofor"&&<label>Araç ve plaka<input required placeholder="Örn. Tır · 34 ABC 123"/></label>}</>}<label>E-posta adresi<input required type="email" defaultValue={role==="sofor"?"sofor@logiway.com":"operasyon@logiway.com"}/></label><label>Şifre<input required type="password" defaultValue="logiwaydemo"/></label>{!register&&<div className="form-row"><label className="check-label"><input type="checkbox"/> Beni hatırla</label><button type="button">Şifremi unuttum</button></div>}<button className="login-button" disabled={busy}>{busy?"Hazırlanıyor…":register?"Hesabımı oluştur":"Giriş yap"}<ArrowRight size={18}/></button><div className="demo-note">Demo sürümünde bilgiler bu cihazda saklanır.</div></form></main></div>
}

function PortalShell({role,children,active,onSelect}){
  const info=roleInfo[role];const Icon=info.icon;
  const menu=role==="yuk-veren"?[["Özet",<ClipboardList size={18}/>],["İlanlarım",<Package size={18}/>],["Teklifler",<Wallet size={18}/>]]:[["Uygun işler",<Package size={18}/>],["Seferlerim",<Route size={18}/>],["Kazançlar",<Wallet size={18}/>]];
  return <div className="portal-shell"><aside><Brand/><div className="workspace-badge"><span><Icon/></span><div><small>ÇALIŞMA ALANI</small><strong>{info.title}</strong></div></div><nav>{menu.map(([label,icon])=><button onClick={()=>onSelect(label)} className={active===label?"active":""} key={label}>{icon}{label}</button>)}</nav><Link to="/giris" className="logout"><LogOut size={17}/> Çıkış yap</Link></aside><main className="portal-main"><header><div><small>{info.title.toUpperCase()} PANELİ</small><strong>Merhaba, {role==="sofor"?"Ahmet":"Kaya Lojistik"}</strong></div><button className="user-avatar" aria-label="Profil bilgileri"><UserRound/></button></header>{children}</main></div>
}

function PageHeading({kicker,title,text,action}){return <section className="portal-heading"><div><span>{kicker}</span><h1>{title}</h1><p>{text}</p></div>{action}</section>}

export function ShipperPortal(){
  const [active,setActive]=useState("Özet");const [loads,setLoads]=useState(()=>JSON.parse(localStorage.getItem("logiway-loads")||"null")||seedLoads);const [modal,setModal]=useState(false);const [success,setSuccess]=useState("");const [acceptedOffer,setAcceptedOffer]=useState(null);
  useEffect(()=>localStorage.setItem("logiway-loads",JSON.stringify(loads)),[loads]);
  function addLoad(e){e.preventDefault();const f=new FormData(e.currentTarget);const next={id:`LW-${2850+loads.length}`,cargo:f.get("cargo"),from:`${f.get("fromCity")} / ${f.get("fromDistrict")}`,to:`${f.get("toCity")} / ${f.get("toDistrict")}`,vehicle:f.get("vehicle"),weight:`${f.get("weight")} ${f.get("unit")}`,price:`${Number(f.get("price")).toLocaleString("tr-TR")} ₺`,date:f.get("pickupDate").split("-").reverse().slice(0,2).join("."),status:"Teklif alıyor",offers:0,packaging:f.get("packaging"),loading:f.get("loading"),payment:f.get("payment"),notes:f.get("notes")};setLoads([next,...loads]);setModal(false);setActive("İlanlarım");setSuccess("İlanınız yayınlandı ve uygun şoförlerle eşleştiriliyor.");setTimeout(()=>setSuccess(""),3500)}
  function acceptOffer(o){setAcceptedOffer(o.id);setLoads(xs=>xs.map(x=>x.id===o.load?{...x,status:"Şoför eşleşti"}:x));setSuccess(`${o.driver} ile eşleşme tamamlandı.`);setTimeout(()=>setSuccess(""),3500)}
  return <PortalShell role="yuk-veren" active={active} onSelect={setActive}>{success&&<div className="success-banner portal-toast"><Check/> {success}</div>}{active==="Özet"&&<><PageHeading kicker="OPERASYON ÖZETİ" title="Yükleriniz kontrol altında." text="İlanlarınızı yayınlayın, gelen teklifleri tek ekrandan yönetin." action={<button className="portal-primary" onClick={()=>setModal(true)}>Yeni yük ilanı <Package size={18}/></button>}/><div className="portal-stats"><article><span>Aktif ilan</span><strong>{loads.filter(x=>x.status==="Teklif alıyor").length}</strong><small>Şu anda yayında</small></article><article><span>Toplam teklif</span><strong>{offers.length}</strong><small>Değerlendirme bekliyor</small></article><article className="dark"><span>Tamamlanan eşleşme</span><strong>{loads.filter(x=>x.status==="Şoför eşleşti").length}</strong><small>Güvenle planlandı</small></article></div><LoadList loads={loads.slice(0,3)} onAll={()=>setActive("İlanlarım")}/></>}{active==="İlanlarım"&&<><PageHeading kicker="İLAN YÖNETİMİ" title="Tüm yük ilanlarınız." text="Aktif, planlanmış ve tamamlanmış ilanlarınızı yönetin." action={<button className="portal-primary" onClick={()=>setModal(true)}>Yeni ilan <Package size={18}/></button>}/><LoadList loads={loads}/></>}{active==="Teklifler"&&<><PageHeading kicker="TEKLİF MERKEZİ" title="Doğru şoförü seçin." text="Doğrulanmış şoförlerin fiyatlarını ve deneyimlerini karşılaştırın."/><section className="offer-list">{offers.map(o=><article key={o.id}><span className="driver-avatar">{o.driver.split(" ").map(x=>x[0]).join("")}</span><div><strong>{o.driver}</strong><small><ShieldCheck/> Doğrulanmış · {o.score} puan · {o.trips} sefer</small></div><div><small>İLAN</small><strong>{o.load}</strong></div><div><small>ARAÇ</small><strong>{o.vehicle}</strong></div><div><small>TEKLİF</small><strong>{o.amount}</strong></div><button disabled={acceptedOffer===o.id} onClick={()=>acceptOffer(o)}>{acceptedOffer===o.id?<><Check/> Eşleşti</>:"Teklifi kabul et"}</button></article>)}</section></>}{modal&&<LoadModal onClose={()=>setModal(false)} onSubmit={addLoad}/>}</PortalShell>
}

function LoadList({loads,onAll}){return <section className="portal-list"><div className="list-head"><div><h2>Yük ilanları</h2><p>Yayınladığınız ilanların güncel durumu</p></div>{onAll&&<button onClick={onAll}>Tümünü gör <ArrowRight size={15}/></button>}</div>{loads.map(x=><article className="load-row" key={x.id}><span className="load-box"><Package/></span><div className="load-route"><strong>{x.from} <ArrowRight/> {x.to}</strong><small>{x.id} · {x.cargo} · {x.vehicle} · {x.weight}</small></div><div><small>HEDEF BÜTÇE</small><strong>{x.price}</strong></div><div><small>TEKLİFLER</small><strong>{x.offers} teklif</strong></div><span className={`portal-status ${x.status==="Teklif alıyor"?"green":""}`}>{x.status}</span><button className="row-action"><ChevronRight/></button></article>)}</section>}

function LoadModal({onClose,onSubmit}){return <div className="portal-modal" role="dialog" aria-modal="true"><form onSubmit={onSubmit}><div className="modal-head"><div><span>YENİ YÜK İLANI</span><h2>Yük ve sefer bilgilerini girin</h2></div><button type="button" onClick={onClose} aria-label="Kapat"><X/></button></div><div className="form-section-title">Yük bilgileri</div><div className="form-grid"><label className="wide">Yükün cinsi<input required name="cargo" placeholder="Örn. Paletli kuru gıda, mobilya, makine parçası"/></label><label>Paketleme tipi<select name="packaging"><option>Paletli</option><option>Kolili</option><option>Çuvallı</option><option>Dökme</option><option>Parça yük</option><option>Diğer</option></select></label><label>Gerekli araç<select name="vehicle"><option>Tır</option><option>Kamyon</option><option>Kamyonet</option><option>Panelvan</option><option>Frigorifik</option><option>Tanker</option><option>Lowbed</option></select></label><label>Ağırlık<input required name="weight" type="number" min="0.1" step="0.1" placeholder="24"/></label><label>Birim<select name="unit"><option>ton</option><option>kg</option><option>palet</option><option>koli</option></select></label></div><div className="form-section-title">Rota ve zamanlama</div><div className="form-grid"><label>Kalkış ili<input required name="fromCity" placeholder="İstanbul"/></label><label>Kalkış ilçesi<input required name="fromDistrict" placeholder="Tuzla"/></label><label>Varış ili<input required name="toCity" placeholder="Ankara"/></label><label>Varış ilçesi<input required name="toDistrict" placeholder="Sincan"/></label><label>Yükleme tarihi<input required name="pickupDate" type="date"/></label><label>Teslim tarihi<input required name="deliveryDate" type="date"/></label><label>Yükleme şekli<select name="loading"><option>Arkadan yükleme</option><option>Yandan yükleme</option><option>Üstten yükleme</option><option>Forklift gerekli</option><option>Vinç gerekli</option></select></label><label>Ödeme şekli<select name="payment"><option>Teslimatta ödeme</option><option>Peşin ödeme</option><option>7 gün vadeli</option><option>15 gün vadeli</option><option>30 gün vadeli</option></select></label><label className="wide">Hedef bütçe (₺)<input required name="price" type="number" min="1" placeholder="38000"/></label><label className="wide">Ek açıklama<textarea name="notes" rows="3" placeholder="Yükleme saati, özel taşıma koşulları veya şoförün bilmesi gerekenler…"/></label></div><div className="modal-actions"><button type="button" onClick={onClose}>Vazgeç</button><button className="login-button">İlanı yayınla ve eşleştir <ArrowRight/></button></div></form></div>}

export function DriverPortal(){
  const [active,setActive]=useState("Uygun işler");const [accepted,setAccepted]=useState(()=>JSON.parse(localStorage.getItem("logiway-trips")||"[]"));const [filter,setFilter]=useState("Tümü");const [notice,setNotice]=useState("");
  useEffect(()=>localStorage.setItem("logiway-trips",JSON.stringify(accepted)),[accepted]);
  const visible=useMemo(()=>filter==="Tümü"?jobs:jobs.filter(x=>x.vehicle===filter),[filter]);const acceptedJobs=jobs.filter(x=>accepted.includes(x.id));
  function accept(job){if(!accepted.includes(job.id))setAccepted([...accepted,job.id]);setNotice(`${job.id} için teklifiniz yük verene gönderildi.`);setTimeout(()=>setNotice(""),3500)}
  return <PortalShell role="sofor" active={active} onSelect={setActive}>{notice&&<div className="success-banner portal-toast"><Check/> {notice}</div>}{active==="Uygun işler"&&<><PageHeading kicker="AKILLI EŞLEŞTİRME" title="Rotanıza uygun yükler." text="Araç ve konum bilgilerinizle en uyumlu ilanlar önce gösterilir." action={<div className="driver-online"><i/> İş almaya açıksınız</div>}/><div className="driver-toolbar"><div>{["Tümü","Tır","Kamyon"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><span>{visible.length} uygun iş</span></div><JobGrid data={visible} accepted={accepted} onAccept={accept}/></>}{active==="Seferlerim"&&<><PageHeading kicker="SEFER TAKİBİ" title="Seferleriniz tek ekranda." text="Teklif verdiğiniz ve devam eden taşıma işlerini takip edin."/><section className="trip-board">{acceptedJobs.length?<JobGrid data={acceptedJobs} accepted={accepted} onAccept={accept}/>:<EmptyState icon={<Route/>} title="Henüz seferiniz yok" text="Uygun işler ekranından bir yüke teklif vererek başlayın." action={()=>setActive("Uygun işler")}/>}</section></>}{active==="Kazançlar"&&<><PageHeading kicker="KAZANÇ ÖZETİ" title="Emeğinizin karşılığını izleyin." text="Tamamlanan seferler ve bekleyen ödemeler burada görünür."/><div className="earnings-grid"><article><span>Bu ay</span><strong>{acceptedJobs.length?"56.400 ₺":"0 ₺"}</strong><small>Tamamlanan 3 sefer</small></article><article><span>Bekleyen ödeme</span><strong>{acceptedJobs.length?"17.500 ₺":"0 ₺"}</strong><small>1 sefer · 7 gün vadeli</small></article><article className="dark"><span>Toplam kazanç</span><strong>{acceptedJobs.length?"248.750 ₺":"0 ₺"}</strong><small>Logiway başlangıcından beri</small></article></div><section className="payment-list"><div className="list-head"><div><h2>Ödeme hareketleri</h2><p>Son sefer ödemeleriniz</p></div></div>{acceptedJobs.length?<><div className="payment-row"><FileCheck2/><div><strong>İstanbul → Ankara</strong><small>LW-2847 · Tamamlandı</small></div><span>+38.000 ₺</span><b>Ödendi</b></div><div className="payment-row"><Clock3/><div><strong>İzmir → Bursa</strong><small>LW-2844 · Teslim edildi</small></div><span>+17.500 ₺</span><b className="waiting">Bekliyor</b></div></>:<EmptyState icon={<Wallet/>} title="Henüz kazanç hareketi yok" text="Tamamlanan seferlerinizin ödemeleri burada listelenecek."/>}</section></>}</PortalShell>
}

function JobGrid({data,accepted,onAccept}){return <section className="job-grid">{data.map(job=><article className="job-card" key={job.id}><div className="match-score">%{job.match} eşleşme</div><div className="job-top"><span>{job.id}</span><strong>{job.price}</strong></div><h3>{job.cargo}</h3><div className="job-route"><div><i/><span><small>KALKIŞ</small><strong>{job.from}</strong></span></div><div className="route-line"/><div><i/><span><small>VARIŞ</small><strong>{job.to}</strong></span></div></div><div className="job-meta"><span><Truck/> {job.vehicle}</span><span><Weight/> {job.weight}</span><span><MapPin/> {job.distance}</span><span><Clock3/> {job.date}</span></div><div className="job-company"><span>{job.company[0]}</span><div><strong>{job.company}</strong><small><ShieldCheck/> Doğrulanmış firma</small></div></div><button disabled={accepted.includes(job.id)} onClick={()=>onAccept(job)} className={accepted.includes(job.id)?"accepted":""}>{accepted.includes(job.id)?<><Check/> Teklif gönderildi</>:<>Teklif ver <ArrowRight/></>}</button></article>)}</section>}
function EmptyState({icon,title,text,action}){return <div className="portal-empty"><span>{icon}</span><h3>{title}</h3><p>{text}</p>{action&&<button onClick={action}>Uygun işleri gör <ArrowRight/></button>}</div>}
